pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Run Tests') {
            steps {
                echo 'Running Maven tests'
                dir('SauceDemo') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed'
        }
        failure {
            echo 'Build or tests failed'
        }
        success {
            echo 'Build and tests successful'
        }
    }

    // This section captures and generates the test reports
    post {
        always {
            // Publishes TestNG results even if the build itself has test failures
            testng targetDir: 'target/surefire-reports', reportFilenamePattern: 'testng-results.xml'
        }
    }

}
