pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Run Tests') {
            steps {
                echo 'Running Maven tests'
                dir('SauceDemo') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed'
        }
        failure {
            echo 'Build or tests failed'
        }
        success {
            echo 'Build and tests successful'
        }
    }
}
